# Generated by Django 3.0.3 on 2020-03-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.CharField(default='https://image.3001.net/images/20200304/15832956271308.jpg', max_length=200, verbose_name='文章封面'),
        ),
        migrations.AddField(
            model_name='links',
            name='image',
            field=models.CharField(default='https://image.3001.net/images/20190330/1553875722169.jpg', max_length=200, verbose_name='友情链接头像'),
        ),
        migrations.AddField(
            model_name='site',
            name='site_avatar',
            field=models.CharField(default='https://image.3001.net/images/20171226/15142933784705.png', max_length=200, verbose_name='我的头像'),
        ),
    ]
