# Generated by Django 3.0.3 on 2020-03-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200306_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='index',
        ),
        migrations.AddField(
            model_name='links',
            name='desc',
            field=models.CharField(default='', max_length=50, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='links',
            name='image',
            field=models.CharField(default='https://image.3001.net/images/20190330/1553875722169.jpg', max_length=200, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='links',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='links',
            name='url',
            field=models.URLField(verbose_name='地址'),
        ),
    ]
