# Generated by Django 3.0.3 on 2020-03-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200307_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='desc',
            field=models.TextField(verbose_name='描述'),
        ),
    ]
