# Generated by Django 3.0.3 on 2020-03-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200307_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='desc',
            field=models.TextField(max_length=250, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='links',
            name='image',
            field=models.URLField(default='https://image.3001.net/images/20190330/1553875722169.jpg', verbose_name='头像'),
        ),
    ]
