# Generated by Django 3.0.3 on 2020-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200307_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.TextField(max_length=100, verbose_name='文章描述'),
        ),
    ]
