# Generated by Django 3.0.3 on 2020-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='fa-home', max_length=30, verbose_name='菜单图标'),
        ),
    ]
